# theme = "autumn"
theme = "keyb1nd"

[editor]
line-number = "relative"
cursorline = true
auto-completion = true
auto-format = true
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = false
snippets = true

